# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "shokupass"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000", "shokupass://*",]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true

[auth.external.google]
enabled = true
secret = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_SECRET)"
client_id = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_ID)"

[auth.external.discord]
enabled = true
secret = "env(SUPABASE_AUTH_EXTERNAL_DISCORD_CLIENT_SECRET)"
client_id = "env(SUPABASE_AUTH_EXTERNAL_DISCORD_CLIENT_ID)"

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"

[experimental]
orioledb_version = ""
