export enum OrderStatus {
  PENDING = "PENDING",
  PAYMENT = "PAYMENT",
  COOKING = "COOKING",
  READY_FOR_PICKUP = "READY_FOR_PICKUP",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  REFUNDED = "REFUNDED",
  DELETED = "DELETED",
}
